name: Build Status

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - '*'
    pull_request:
      branches:
        - '*'

jobs:
  build:
    strategy:
      matrix:
        java-version: [21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew --no-daemon build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: |
            build/libs/*.jar
            !build/libs/*-slim.jar
