name: Upload to GHCR

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew installShadowDist
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JAVA_VERSON=${{ matrix.java-version }}
            VERSION=${{ github.ref_name }}
